apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.sql.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.sql.name }}
    project: {{ .Values.global.projectName }}

spec:
  type: {{ .Values.sql.service.type }}
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: sql 
  selector:
    app.kubernetes.io/name: {{ .Values.sql.name }}
