apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ans-semaphore.fullname" . }}
  labels:
    {{- include "ans-semaphore.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "ans-semaphore.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ans-semaphore.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.semaphore.image.repository }}:{{ .Values.semaphore.image.tag }}"
          imagePullPolicy: {{ .Values.semaphore.image.pullPolicy }}
          env:
            - name: SEMAPHORE_DB_DIALECT
              value: {{ .Values.semaphore.env.SEMAPHORE_DB_DIALECT }}
            - name: SEMAPHORE_DB
              value: {{ .Values.semaphore.env.SEMAPHORE_DB }}
            - name: SEMAPHORE_DB_USER
              value: {{ .Values.semaphore.env.SEMAPHORE_DB_USER }}
            - name: SEMAPHORE_DB_PASS
              value: {{ .Values.semaphore.env.SEMAPHORE_DB_PASS }}
            - name: SEMAPHORE_DB_HOST
              value: {{ .Values.semaphore.env.SEMAPHORE_DB_HOST }}
            - name: SEMAPHORE_DB_PORT
              value: {{ .Values.semaphore.env.SEMAPHORE_DB_PORT | quote }}
            - name: SEMAPHORE_PLAYBOOK_PATH
              value: {{ .Values.semaphore.env.SEMAPHORE_PLAYBOOK_PATH }}
            - name: SEMAPHORE_ADMIN_PASSWORD
              value: {{ .Values.semaphore.env.SEMAPHORE_ADMIN_PASSWORD }}
            - name: SEMAPHORE_ADMIN_EMAIL
              value: {{ .Values.semaphore.env.SEMAPHORE_ADMIN_EMAIL }}
            - name: SEMAPHORE_ADMIN_NAME
              value: {{ .Values.semaphore.env.SEMAPHORE_ADMIN_NAME }}
            - name: SEMAPHORE_ADMIN
              value: {{ .Values.semaphore.env.SEMAPHORE_ADMIN }}
            - name: SEMAPHORE_ACCESS_KEY_ENCRYPTION
              value: {{ .Values.semaphore.env.SEMAPHORE_ACCESS_KEY_ENCRYPTION }}

          ports:
            - name: http
              containerPort: {{ .Values.semaphore.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
