apiVersion: v1
kind: Service
metadata:
  name: {{ include "semaphore.fullname" . }}
  labels:
    {{- include "semaphore.labels" . | nindent 4 }}
spec:
  type: {{ .Values.semaphore.service.type }}
  ports:
    - port: {{ .Values.semaphore.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if eq .Values.semaphore.service.type "NodePort" }}
      nodePort: {{ .Values.semaphore.service.nodePort }}
      {{- end }}
  selector:
    {{- include "semaphore.selectorLabels" . | nindent 4 }}

