apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
    project: {{ .Values.global.projectName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.name }}
      project: {{ .Values.global.projectName }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.name }}
        project: {{ .Values.global.projectName }}
    spec:
      volumes:
        - name: {{ .Values.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.volume.claimName }}
      containers:
        - name: {{ .Values.name }}
          volumeMounts:
            - name: {{ .Values.volume.name }}
              mountPath: {{ .Values.volume.mountPath }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: root
          - name: MYSQL_RANDOM_ROOT_PASSWORD
            value: "{{ .Values.environment.MYSQL_RANDOM_ROOT_PASSWORD }}"
          - name: MYSQL_DATABASE
            value: "{{ .Values.environment.MYSQL_DATABASE }}"
          - name: MYSQL_USER
            value: "{{ .Values.environment.MYSQL_USER }}"
          - name: MYSQL_PASSWORD
            value: "{{ .Values.environment.MYSQL_PASSWORD }}"
          ports:
            - name: sql
              containerPort: 3306
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 5
            tcpSocket:
              port: 3306
          readinessProbe:
            initialDelaySeconds: 5
            tcpSocket:
              port: 3306
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
