apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volume.claimName }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
    project: {{ .Values.global.projectName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.storageSize }}
