# Default values for semaphore.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

env:
  SEMAPHORE_DB_DIALECT: mysql
  SEMAPHORE_DB: semaphore
  SEMAPHORE_DB_USER: semaphore
  SEMAPHORE_DB_PASS: semaphore
  SEMAPHORE_DB_HOST: semaphore-mariadb.semaphore.svc.cluster.local
  SEMAPHORE_DB_PORT: 3306
  SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
  SEMAPHORE_ADMIN_PASSWORD: admin-password
  SEMAPHORE_ADMIN_EMAIL: admin@example.com
  SEMAPHORE_ADMIN_NAME: admin
  SEMAPHORE_ADMIN: admin
  SEMAPHORE_ACCESS_KEY_ENCRYPTION: gs72mPntFATGJs9qK0pQ0rKtfidlexiMjYCH9gWKhTU=

service:
    port: 3000

image:
  repository: semaphoreui/semaphore
  pullPolicy: IfNotPresent
  tag: "v2.8.90"

ingress:
  enabled: true
  tls: true

volume:
  enabled: true
  name: semaphore-pv
  claimName: semaphore-pvc
  storageSize: 1Gi
  mountPath: /mnt/data

mariadb:
  enabled: true
  architecture: standalone
  auth:
    rootPassword: semaphore
    database: semaphore
    username: semaphore
    password: semaphore
  primary:
    persistence:
      enabled: true
      storageClass: ""
      accessModes:
        - ReadWriteOnce
      size: 2Gi
